### PR TITLE
fix: Fix false positive by ignoring text that lives over an image overlay

### PR DESCRIPTION
**Pull request by DaveTryon**
Closes: #59 

Note: This adds a threshold value of 100,000, which is somewhat arbitrary based on the images in the unit tests. The largest value reached in the current unit tests is 61.425. There's a possibility of a non-overlay text reaching this threshold--if that occurs, then that scanline will be ignored and scanning will continue with other scanlines. It's a heuristic, but intended to err on the side of fewer false positives.

## Requester Review Items

- [x] Ensure the Pull Request is into develop.
- [x] Test coverage has not gone down.
- [x] Documentation updated or not needed. (Wiki, Issues, etc)
- [x] Angular Type leads to proper Semantic Version.

## Dev Team Review Items

To be filled out by @dequelabs/mobile.

- [x] Ensure the Requester did not lie. Chastise them politely if they did.
- [ ] Code Quality review.
- [x] Changes to Axe*.java classes are minimal, appropriate, and versioned properly.
  - [x] Serialized Axe objects have not changed.
  - [x] Public API has not changed.

## Code Owner Review Items

To be filled out by @dequelabs/mobileadmin.

- [x] Any Rules package changes lead to proper Semantic Version.
- [x] Security Review.

## Merger Review Items

- [ ] Ensure commit message matches title before squashing.

### CODE REVIEW

**Comment by chriscm2006** [comment]
Thanks @DaveTryon

**Comment by chriscm2006** [comment]
@DaveTryon I don't think this is the way we should solve this problem, though your test case is super helpful! Would you mind if I pulled your branch down and tweaked some other paramaters and asked you to review them? 

The problem your test case exhibits is solved not by "overlay detection" but by our gradient background logic which "should" but obviously isn't handling this scenario. I would prefer to tweak existing parameters to creating a new one. The problem with the logic as you've tweaked it, is that it will filter out many cases that we are currently detecting correctly.

If this is good with you, I'll take your logic and ensure your test case works, but by tweaking some other parameters. If there are any other test cases you want to add before I do this let me know!

**Comment by DaveTryon** [comment]
@chriscm2006, I agree that this is not an elegant fix. If there's a way to adjust the gradient algorithm to handle this case, then I'm all for that. Please feel free to fork this branch--I'll add a few more images to serve as test cases, just to broaden the data set that gets checked. I'll leave the PR open until I get the chance to add the additional test cases (probably on 1/31)

**Comment by DaveTryon** [comment]
@chriscm2006, I've added a few more test cases to https://github.com/DaveTryon/axe-android/tree/TextOverlayBugDemo. Please feel free to use these as appropriate to tune the color contrast handling. I noticed that some of the new test cases report low confidence instead of high, so the final form of the test cases may need to be tweaked accordingly. My intent here was to capture some interesting test cases. I'll close out this PR now.

**Pull request closed without merging**
